### PR TITLE
Remove babel dependency

### PR DESCRIPTION
**Pull request by igl**
Leave the babel strategy up to the user. 
Slimmer package. 
Sparkles. :sparkles:

### CODE REVIEW

**Comment by codella** [comment]
I like this!

**Comment by igl** [comment]
Is Michael Jackson still alive?

**Comment by mjackson** [comment]
Doesn't this just make it more difficult for people to use? Now, in order to use ES2015 in their JS they have to know about babel and stuff.. which I guess they probably know anyway. But still..

**Comment by igl** [comment]
Adding those 3 lines yourself isn't a big deal is it? Especially for someone who wants to render react components over stdio. 

Also: Node 5.x brings ~59% native ES6/ES2015 coverage. No need to transpile much.

**Comment by mjackson** [comment]
@igl I merged and released this in `v3.0.0-0`. Please test and confirm it works as you need it to so I can cut a final release. Thanks!

**Comment by mjackson** [comment]
Just cut v3.0 https://github.com/mjackson/react-stdio/commit/0d070c7dacb8f2b49659e772de7e6a6233193ab5

**Pull request merged**
